### ISSUE TITLE
可否增加搜索功能

### ISSUE THREAD

**Issue by DZDZzzZ** [fallingrust/Jellyfin-Plugin-AdultsSubtitle#9]
由于我的片名和官方可能有些出入，导致直接搜索的时候找不到，是否可以增加一个搜索框，去搜索对应的字幕

**Comment by fallingrust** [comment]
![image](https://github.com/user-attachments/assets/a8cea7b9-9d62-41b8-a0de-49b523656a80)
![image](https://github.com/user-attachments/assets/1d1d9e6a-914f-4f6c-a2b5-5e8ea767ba8a)

这个Jellyfin自带的吧，

**Comment by fallingrust** [comment]
现在jellyfin自带字幕搜索框，所以没有开发计划，建议使用官方名称配合[https://github.com/metatube-community/jellyfin-plugin-metatube](url)，食用更佳
